### ISSUE TITLE
Modernize prow.istio.io

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1396]
- [x] Update the existing cluster to head
  - [x] Apply [breaking changes](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md) since November to deployments and update, which should get things working - https://github.com/istio/test-infra/pull/1399
      - [x] [Asking](https://istio.slack.com/archives/C6FCV6WN4/p1562019014474000) whether any jobs depend on the default service account (assuming no)
      - [x] Gerrit is irrelevant
      - [x] Create hook rbac
      - [x] build clusters are so far irrelevant
      - [x] run_after_success now irrelevant (yay!)
      - [x] Need to set `--dry-run=false` for horologium and sinker
      - [x] Added explicit `--config-path` flags
  - [x] We will probably miss something, so figure this out and fix it. - https://github.com/istio/test-infra/pull/1406 https://github.com/istio/test-infra/pull/1410

Other activity:
- [x] Create a separate cluster to run jobs and move jobs there
- [x] Clone the prow.k8s.io automation we use  to update prow daily
  - [x] bump script https://github.com/istio/test-infra/pull/1420
  - [x] create periodic job to run the bump script every day
  - [x] Create postsubmit to apply changes to prow/cluster/*.yaml files on merge
- [x] Create an https redirect - https://github.com/istio/test-infra/pull/1427
- [x] Determine if branch protector is used (yes)
  - [x] If so update branch protector and run it before updating other components - https://github.com/istio/test-infra/pull/1397
- [x] Setup ghproxy - https://github.com/istio/test-infra/pull/1428 https://github.com/istio/test-infra/pull/1426
- [x] Migrate branch protector from a cronjob to prowjob (easier to work with, more accessible debugging options)
- [x] Oncall members need to join istio org ([example](https://github.com/istio/community/issues/195))
  - [x] fejta - https://github.com/istio/community/issues/195
  - [x] @cjwagner - https://github.com/istio/community/issues/197 
  - [x] @katharine
  - [x] @michelle192837
  - [x] @chases2
- [x] Switch job viewer from gubernator to spyglass - https://github.com/istio/test-infra/issues/1239 
- [x] Setup RBE for any bazel activity (which at least test-infra uses) - https://github.com/istio/test-infra/pull/1400
- [ ] Delete prow code in istio/test-infra
- [ ] Use bazel to deploy k8s resources
- [x] ~setup `@//:nogo_vet`, #1597~
- [x] setup [PR status oauth](https://github.com/kubernetes/test-infra/blob/master/prow/docs/pr_status_setup.md), #1807
- [ ] investigate serving gubernator on gubernator.istio.io
- [x] turn on status-reconciler

Consider using the following:
- [x] ~label_sync - https://github.com/istio/istio/issues/15305~
- [ ] peribolos - https://github.com/istio/test-infra/issues/1425
- [x] PR dashboard - https://github.com/istio/test-infra/issues/1423
- [x] checkconfig - https://github.com/istio/test-infra/issues/1415
- [ ] automate tasks with commenter - https://github.com/istio/test-infra/issues/1431
- [x] lgtm via github review - https://github.com/istio/test-infra/issues/1433

Contact https://go.k8s.io/oncall for assistance.

**Comment by fejta** [comment]
July 1 status:

* Gained access to slack, will post updates to #oncall and/or #test-and-release
* Gained access to istio-testing project
* Gained access to prow us-west1-a cluster in istio-testing
  * service account is `istio-prow-test-job@istio-testing.iam.gserviceaccount.com`
  * 1.12.8-gke.10
  * 5 node pools, all cos, 100G pd boot
    * test-pool - 20 nodes, n1-standard-8
    * prod-pool - 6, n1-standard-4
    * ssd-build-pool - 10, n1-stanard-16 (lol no ssd?!)
    * new-test-pool - 20, n1-standard-16
    * test-pool-2 - 20, n1-standard-8
* Determined we do have branch protector running.
* Forked test-infra and setup local git 
* Updated branchprotector and ran successfully

**Comment by fejta** [comment]
Upgrade is ready to go, will apply tomorrow. Sent FYI to https://discuss.istio.io/t/large-prow-upgrade-tomorrow/2914

**Comment by fejta** [comment]
Applying #1399 now

**Comment by cjwagner** [comment]
> Delete prow code in istio/test-infra

What code is this referring to?

**Comment by fejta** [comment]
> What code is this referring to?

This repo vendors k/ti

**Comment by cjwagner** [comment]
https redirect and ghproxy setup are done now.
checkconfig presubmit and associated config fixes are ready in this PR: https://github.com/istio/test-infra/pull/1430

**Comment by cjwagner** [comment]
Lets also add the [`status-reconciler`](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/status-reconciler#status-reconciler) to the list.

**Comment by fejta** [comment]
Done
