### ISSUE TITLE
umbrella: test slowness on prow

### ISSUE THREAD

**Issue by fejta** [istio/test-infra#1547]
Lots of jobs seem to be performing worse recently and/or worse than they were on circleci

- [ ] release unit tests https://github.com/istio/test-infra/issues/1546
- [ ] unit tests - https://github.com/istio/test-infra/issues/1461
- [ ] race tests https://github.com/istio/test-infra/issues/1524

Need to figure out why

/assign
/cc @cjwagner @howardjohn @utka

**Comment by fejta** [comment]
Most important right now is to improve the speed of the release tests so we can release in a timely manner.

**Comment by fejta** [comment]
This was mitigated by power cycling the nodes. There may be some GKE/kubernetes bug impacting things, which is being investigated elsewhere

/close
